context:
  version: 1.13.0

package:
  name: bibtex-tidy
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/bibtex-tidy/-/bibtex-tidy-${{ version }}.tgz
  sha256: 441a55d7496decda9fd37da7594a03cefc84a6b6c93f247e4a4c501ef6c85a6e

build:
  number: 0
  noarch: generic

requirements:
  host:
    - nodejs
  run:
    - nodejs

tests:
  - script:
      - bibtex-tidy --help

about:
  license: MIT
  license_file: LICENSE
  summary: Cleaner and Formatter for BibTeX files
  homepage: https://github.com/FlamingTempura/bibtex-tidy
  repository: https://github.com/FlamingTempura/bibtex-tidy

extra:
  recipe-maintainers:
    - danielnachun
